# Generated by Django 4.2.7 on 2023-11-26 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField()),
                ('status', models.TextField(blank=True, default='')),
                ('freight_cost', models.FloatField()),
                ('coupon', models.BooleanField()),
                ('discount', models.FloatField()),
                ('final_value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.payment')),
                ('name', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('card_expiration_date', models.CharField(max_length=10)),
            ],
            bases=('store.payment',),
        ),
        migrations.CreateModel(
            name='Pix',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.payment')),
                ('key', models.CharField(max_length=250)),
            ],
            bases=('store.payment',),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.payment')),
                ('barcode', models.CharField(max_length=250)),
                ('recipient_name', models.CharField(max_length=250)),
                ('recipient_cpf', models.CharField(max_length=14)),
            ],
            bases=('store.payment',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('status', models.CharField(max_length=250)),
                ('value', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
